/**
 * File: q_shared.ts
 * Purpose: Expose the first gameplay runtime helpers used by the Quake II door/trigger port.
 *
 * This file is not a direct source port.
 * It is a package entry point for gameplay-facing runtime modules.
 *
 * Dependencies:
 * - packages/game/src/runtime.ts
 * - packages/game/src/g_utils.ts
 */

export {
  GAME_API_VERSION,
  MAX_ENT_CLUSTERS,
  solid_t
} from "./game.js";

export {
  getMonsterFlashOffset,
  monster_flash_offset,
  MZ2_CARRIER_GRENADE,
  MZ2_CARRIER_MACHINEGUN_L1,
  MZ2_CARRIER_MACHINEGUN_L2,
  MZ2_CARRIER_MACHINEGUN_R1,
  MZ2_CARRIER_MACHINEGUN_R2,
  MZ2_CARRIER_RAILGUN,
  MZ2_CARRIER_ROCKET_1,
  MZ2_CARRIER_ROCKET_2,
  MZ2_CARRIER_ROCKET_3,
  MZ2_CARRIER_ROCKET_4,
  MZ2_DAEDALUS_BLASTER,
  MZ2_MEDIC_BLASTER_2,
  MZ2_STALKER_BLASTER,
  MZ2_TURRET_BLASTER,
  MZ2_TURRET_MACHINEGUN,
  MZ2_TURRET_ROCKET,
  MZ2_WIDOW2_BEAMER_1,
  MZ2_WIDOW2_BEAMER_2,
  MZ2_WIDOW2_BEAMER_3,
  MZ2_WIDOW2_BEAMER_4,
  MZ2_WIDOW2_BEAMER_5,
  MZ2_WIDOW2_BEAM_SWEEP_1,
  MZ2_WIDOW2_BEAM_SWEEP_10,
  MZ2_WIDOW2_BEAM_SWEEP_11,
  MZ2_WIDOW2_BEAM_SWEEP_2,
  MZ2_WIDOW2_BEAM_SWEEP_3,
  MZ2_WIDOW2_BEAM_SWEEP_4,
  MZ2_WIDOW2_BEAM_SWEEP_5,
  MZ2_WIDOW2_BEAM_SWEEP_6,
  MZ2_WIDOW2_BEAM_SWEEP_7,
  MZ2_WIDOW2_BEAM_SWEEP_8,
  MZ2_WIDOW2_BEAM_SWEEP_9,
  MZ2_WIDOW_BLASTER,
  MZ2_WIDOW_BLASTER_0,
  MZ2_WIDOW_BLASTER_10,
  MZ2_WIDOW_BLASTER_100,
  MZ2_WIDOW_BLASTER_10L,
  MZ2_WIDOW_BLASTER_20,
  MZ2_WIDOW_BLASTER_20L,
  MZ2_WIDOW_BLASTER_30,
  MZ2_WIDOW_BLASTER_30L,
  MZ2_WIDOW_BLASTER_40,
  MZ2_WIDOW_BLASTER_40L,
  MZ2_WIDOW_BLASTER_50,
  MZ2_WIDOW_BLASTER_50L,
  MZ2_WIDOW_BLASTER_60,
  MZ2_WIDOW_BLASTER_60L,
  MZ2_WIDOW_BLASTER_70,
  MZ2_WIDOW_BLASTER_70L,
  MZ2_WIDOW_BLASTER_80,
  MZ2_WIDOW_BLASTER_90,
  MZ2_WIDOW_BLASTER_SWEEP1,
  MZ2_WIDOW_BLASTER_SWEEP2,
  MZ2_WIDOW_BLASTER_SWEEP3,
  MZ2_WIDOW_BLASTER_SWEEP4,
  MZ2_WIDOW_BLASTER_SWEEP5,
  MZ2_WIDOW_BLASTER_SWEEP6,
  MZ2_WIDOW_BLASTER_SWEEP7,
  MZ2_WIDOW_BLASTER_SWEEP8,
  MZ2_WIDOW_BLASTER_SWEEP9,
  MZ2_WIDOW_DISRUPTOR,
  MZ2_WIDOW_PLASMABEAM,
  MZ2_WIDOW_RAIL,
  MZ2_WIDOW_RAIL_LEFT,
  MZ2_WIDOW_RAIL_RIGHT,
  MZ2_WIDOW_RUN_1,
  MZ2_WIDOW_RUN_2,
  MZ2_WIDOW_RUN_3,
  MZ2_WIDOW_RUN_4,
  MZ2_WIDOW_RUN_5,
  MZ2_WIDOW_RUN_6,
  MZ2_WIDOW_RUN_7,
  MZ2_WIDOW_RUN_8
} from "./m_flash.js";

export {
  AI_BRUTAL,
  AI_COMBAT_POINT,
  AI_DUCKED,
  AI_GOOD_GUY,
  AI_HOLD_FRAME,
  AI_LOST_SIGHT,
  AI_MEDIC,
  AI_NOSTEP,
  AI_PURSUIT_LAST_SEEN,
  AI_PURSUE_NEXT,
  AI_PURSUE_TEMP,
  AI_RESURRECTING,
  AI_SOUND_TARGET,
  AI_STAND_GROUND,
  AI_TEMP_STAND_GROUND,
  ANIM_ATTACK,
  ANIM_BASIC,
  ANIM_DEATH,
  ANIM_JUMP,
  ANIM_PAIN,
  ANIM_REVERSE,
  ANIM_WAVE,
  ARMOR_BODY,
  ARMOR_COMBAT,
  ARMOR_JACKET,
  ARMOR_NONE,
  ARMOR_SHARD,
  AS_MELEE,
  AS_MISSILE,
  AS_SLIDING,
  AS_STRAIGHT,
  BODY_QUEUE_SIZE,
  CENTER_HANDED,
  LEFT_HANDED,
  CLOFS,
  FALL_TIME,
  FFL_NOSPAWN,
  FFL_SPAWNTEMP,
  FL_FLY,
  FL_INWATER,
  FL_IMMUNE_LAVA,
  FL_IMMUNE_SLIME,
  FL_PARTIALGROUND,
  FL_SWIM,
  FL_WATERJUMP,
  fieldtype_t,
  FOFS,
  GAMEVERSION,
  GIB_METALLIC,
  GIB_ORGANIC,
  ITEM_INDEX,
  ITEM_NO_TOUCH,
  ITEM_TARGETS_USED,
  ITEM_TRIGGER_SPAWN,
  IT_AMMO,
  IT_ARMOR,
  IT_KEY,
  IT_POWERUP,
  IT_STAY_COOP,
  IT_WEAPON,
  LLOFS,
  MELEE_DISTANCE,
  movetype_t,
  PNOISE_IMPACT,
  PNOISE_SELF,
  PNOISE_WEAPON,
  RANGE_FAR,
  RANGE_MELEE,
  RANGE_MID,
  RANGE_NEAR,
  RIGHT_HANDED,
  crandom,
  random,
  SFL_CROSS_TRIGGER_1,
  SFL_CROSS_TRIGGER_2,
  SFL_CROSS_TRIGGER_3,
  SFL_CROSS_TRIGGER_4,
  SFL_CROSS_TRIGGER_5,
  SFL_CROSS_TRIGGER_6,
  SFL_CROSS_TRIGGER_7,
  SFL_CROSS_TRIGGER_8,
  SFL_CROSS_TRIGGER_MASK,
  SPAWNFLAG_NOT_COOP,
  SPAWNFLAG_NOT_DEATHMATCH,
  SPAWNFLAG_NOT_EASY,
  SPAWNFLAG_NOT_HARD,
  SPAWNFLAG_NOT_MEDIUM,
  STOFS,
  TAG_GAME,
  TAG_LEVEL,
  createGameLocals,
  createLevelLocals,
  createSpawnTemp,
  damage_t,
  svc_inventory,
  svc_layout,
  svc_muzzleflash,
  svc_muzzleflash2,
  svc_stufftext,
  svc_temp_entity,
  world
} from "./g_local.js";

export {
  FRAME_stand201,
  FRAME_stand202,
  FRAME_stand203,
  FRAME_stand204,
  FRAME_stand205,
  FRAME_stand206,
  FRAME_stand207,
  FRAME_stand208,
  FRAME_stand209,
  FRAME_stand210,
  FRAME_stand211,
  FRAME_stand212,
  FRAME_stand213,
  FRAME_stand214,
  FRAME_stand215,
  FRAME_stand216,
  FRAME_stand217,
  FRAME_stand218,
  FRAME_stand219,
  FRAME_stand220,
  FRAME_stand221,
  FRAME_stand222,
  FRAME_stand223,
  FRAME_stand224,
  FRAME_stand225,
  FRAME_stand226,
  FRAME_stand227,
  FRAME_stand228,
  FRAME_stand229,
  FRAME_stand230,
  FRAME_stand231,
  FRAME_stand232,
  FRAME_stand233,
  FRAME_stand234,
  FRAME_stand235,
  FRAME_stand236,
  FRAME_stand237,
  FRAME_stand238,
  FRAME_stand239,
  FRAME_stand240,
  FRAME_stand241,
  FRAME_stand242,
  FRAME_stand243,
  FRAME_stand244,
  FRAME_stand245,
  FRAME_stand246,
  FRAME_stand247,
  FRAME_stand248,
  FRAME_stand249,
  FRAME_stand250,
  FRAME_stand251,
  FRAME_stand252,
  FRAME_stand253,
  FRAME_stand254,
  FRAME_stand255,
  FRAME_stand256,
  FRAME_stand257,
  FRAME_stand258,
  FRAME_stand259,
  FRAME_stand260,
  MODEL_SCALE
} from "./m_rider.js";

export * as actorFrames from "./m_actor.js";
export * as berserkFrames from "./m_berserk.js";
export * as boss2Frames from "./m_boss2.js";
export * as boss3Frames from "./m_boss3.js";
export * as boss31Frames from "./m_boss31.js";
export * as boss32Frames from "./m_boss32.js";
export * as brainFrames from "./m_brain.js";
export * as chickFrames from "./m_chick.js";
export * as flipperFrames from "./m_flipper.js";
export * as floatFrames from "./m_float.js";
export * as flyerFrames from "./m_flyer.js";
export * as gladiatorFrames from "./m_gladiator.js";
export * as gunnerFrames from "./m_gunner.js";
export * as hoverFrames from "./m_hover.js";
export * as infantryFrames from "./m_infantry.js";
export * as insaneFrames from "./m_insane.js";
export * as medicFrames from "./m_medic.js";
export * as mutantFrames from "./m_mutant.js";
export * as parasiteFrames from "./m_parasite.js";
export * as playerFrames from "./m_player.js";
export * as soldierFrames from "./m_soldier.js";
export * as supertankFrames from "./m_supertank.js";
export * as tankFrames from "./m_tank.js";
export * as monsterFlash from "./m_flash.js";

export type {
  GameClientServerFields,
  GameEdictServerFields,
  GetGameApi,
  edict_t,
  game_export_t,
  game_import_t,
  gclient_t,
  link_t
} from "./game.js";

export {
  AREA_SOLID,
  AREA_TRIGGERS,
  BoxEdicts,
  classifyGameEntity,
  attachGameClient,
  DOOR_CRUSHER,
  DOOR_NOMONSTER,
  DOOR_REVERSE,
  DOOR_START_OPEN,
  DOOR_TOGGLE,
  DOOR_X_AXIS,
  DOOR_Y_AXIS,
  DEFAULT_DEATHMATCH_SHOTGUN_COUNT,
  DEFAULT_BULLET_HSPREAD,
  DEFAULT_BULLET_VSPREAD,
  DEFAULT_SHOTGUN_COUNT,
  DEFAULT_SHOTGUN_HSPREAD,
  DEFAULT_SHOTGUN_VSPREAD,
  DEFAULT_SSHOTGUN_COUNT,
  DAMAGE_BULLET,
  DAMAGE_ENERGY,
  DAMAGE_NO_KNOCKBACK,
  DAMAGE_RADIUS,
  DAMAGE_TIME,
  DEAD_DEAD,
  DEAD_DYING,
  DEAD_NO,
  DEAD_RESPAWNABLE,
  DROPPED_ITEM,
  DROPPED_PLAYER_ITEM,
  FL_GODMODE,
  FL_IMMUNE_LASER,
  FL_NO_KNOCKBACK,
  FL_NOTARGET,
  FL_POWER_ARMOR,
  FL_RESPAWN,
  FL_TEAMSLAVE,
  FRAMETIME,
  MOVETYPE_BOUNCE,
  MOVETYPE_FLY,
  MOVETYPE_NOCLIP,
  MOVETYPE_FLYMISSILE,
  MOD_BLASTER,
  MOD_BFG_BLAST,
  MOD_BFG_EFFECT,
  MOD_BFG_LASER,
  MOD_CHAINGUN,
  MOD_G_SPLASH,
  MOD_GRENADE,
  MOD_HANDGRENADE,
  MOD_HELD_GRENADE,
  MOD_HG_SPLASH,
  MOD_HIT,
  MOD_HYPERBLASTER,
  MOD_MACHINEGUN,
  MOD_RAILGUN,
  MOD_ROCKET,
  MOD_R_SPLASH,
  SOLID_BBOX,
  MOD_SHOTGUN,
  MOD_SSHOTGUN,
  MOVETYPE_NONE,
  MOVETYPE_PUSH,
  MOVETYPE_STEP,
  MOVETYPE_STOP,
  MOVETYPE_TOSS,
  MOVETYPE_WALK,
  POWER_ARMOR_NONE,
  POWER_ARMOR_SCREEN,
  POWER_ARMOR_SHIELD,
  WEAP_BFG,
  WEAP_BLASTER,
  WEAP_CHAINGUN,
  WEAP_GRENADELAUNCHER,
  WEAP_GRENADES,
  WEAP_HYPERBLASTER,
  WEAP_MACHINEGUN,
  WEAP_RAILGUN,
  WEAP_ROCKETLAUNCHER,
  WEAP_SHOTGUN,
  WEAP_SUPERSHOTGUN,
  PLAT_LOW_TRIGGER,
  SPLASH_BLOOD,
  SPLASH_BLUE_WATER,
  SPLASH_BROWN_WATER,
  SPLASH_LAVA,
  SPLASH_SLIME,
  SPLASH_SPARKS,
  SPLASH_UNKNOWN,
  SOLID_NOT,
  SOLID_BSP,
  SOLID_TRIGGER,
  STATE_BOTTOM,
  STATE_DOWN,
  STATE_TOP,
  STATE_UP,
  SVF_DEADMONSTER,
  SVF_MONSTER,
  SVF_NOCLIENT,
  ammo_t,
  createGameRuntimeFromBspMap,
  createGameRuntimeFromBspEntities,
  createRuntimeEntity,
  drainGameCenterprintEvents,
  drainGameConfigstringUpdates,
  drainGameCprintfEvents,
  drainMonsterMuzzleFlashEvents,
  drainPlayerMuzzleFlashEvents,
  drainGameTempEntityEvents,
  drainGameSoundEvents,
  emitGameCenterprint,
  emitGameTempEntity,
  emitGameCprintf,
  emitGameSound,
  emitMonsterMuzzleFlash,
  emitRegisteredGameSound,
  emitPlayerMuzzleFlash,
  findRuntimeEntitiesByTargetname,
  getRuntimeEntityLabel,
  isDynamicBoxEntity,
  isInlineBspEntity,
  isRuntimeTriggerEntity,
  linkGameEntity,
  registerGameImage,
  registerGameModel,
  registerGameSound,
  setGameEntityModel,
  setGameConfigstring,
  refreshEntitySpatialState,
  runPendingThinks,
  spawnGameEntity,
  unlinkGameEntity,
  useGameEntity,
  weaponstate_t
} from "./runtime.js";

export {
  CanDamage,
  CheckTeamDamage,
  CheckPowerArmor,
  Killed,
  M_ReactToDamage,
  SpawnDamage,
  T_Damage,
  T_RadiusDamage
} from "./g_combat.js";

export {
  ChaseNext,
  ChasePrev,
  GetChaseTarget,
  UpdateChaseCam
} from "./g_chase.js";

export {
  ClientCommand as GameCommandsClientCommand,
  ClientTeam,
  Cmd_Drop_f,
  Cmd_Give_f,
  Cmd_God_f,
  Cmd_Inven_f,
  Cmd_InvDrop_f,
  Cmd_InvUse_f,
  Cmd_Kill_f,
  Cmd_Noclip_f,
  Cmd_Notarget_f,
  Cmd_PlayerList_f,
  Cmd_Players_f,
  Cmd_PutAway_f,
  Cmd_Say_f,
  Cmd_Use_f,
  Cmd_Wave_f,
  Cmd_WeapLast_f,
  Cmd_WeapNext_f,
  Cmd_WeapPrev_f,
  OnSameTeam,
  PlayerSort,
  SelectNextItem,
  SelectPrevItem,
  ValidateSelectedItem
} from "./g_cmds.js";

export {
  AI_SetSightClient,
  FacingIdeal,
  FindTarget,
  FoundTarget,
  HuntTarget,
  M_CheckAttack,
  ai_charge,
  ai_checkattack,
  ai_move,
  ai_run,
  ai_run_melee,
  ai_run_missile,
  ai_run_slide,
  ai_stand,
  ai_turn,
  ai_walk,
  infront,
  range,
  visible
} from "./g_ai.js";

export {
  G_Find,
  G_CopyString,
  G_FreeEdict,
  G_InitEdict,
  G_PickTarget,
  G_ProjectSource,
  G_SetMovedir,
  G_Spawn,
  G_UseTargets,
  KillBox,
  findradius,
  tv,
  vectoyaw,
  vectoangles,
  vtos
} from "./g_utils.js";

export {
  ED_CallSpawn,
  G_FindTeams,
  SpawnEntities,
  SP_worldspawn,
  initializeDoorPlanEntities
} from "./g_spawn.js";

export {
  Add_Ammo,
  ArmorIndex,
  DoRespawn,
  Drop_Ammo,
  Drop_General,
  Drop_Item,
  FindWeaponItemByThink,
  FindItem,
  FindItemByClassname,
  GetArmorInfoByItem,
  GetAmmoItemForWeapon,
  GetGameItems,
  GetItemByIndex,
  InitItems,
  MegaHealth_think,
  PowerArmorType,
  Pickup_Adrenaline,
  Pickup_Ammo,
  Pickup_AncientHead,
  Pickup_Armor,
  Pickup_Bandolier,
  Pickup_Health,
  Pickup_Key,
  Pickup_Pack,
  Pickup_PowerArmor,
  Pickup_Powerup,
  PrecacheItem,
  SP_item_health,
  SP_item_health_large,
  SP_item_health_mega,
  SP_item_health_small,
  SetRespawn,
  SetItemNames,
  SpawnItem,
  Touch_Item,
  Use_Breather,
  Use_Envirosuit,
  Use_Invulnerability,
  Use_Item,
  Use_PowerArmor,
  Use_Quad,
  Use_Silencer,
  droptofloor
} from "./g_items.js";

export {
  SP_func_areaportal,
  SP_func_clock,
  SP_func_explosive,
  SP_info_notnull,
  SP_info_null,
  SP_light,
  SP_light_mine1,
  SP_light_mine2,
  SP_misc_banner,
  SP_misc_blackhole,
  SP_misc_bigviper,
  SP_misc_deadsoldier,
  SP_misc_easterchick,
  SP_misc_easterchick2,
  SP_misc_eastertank,
  SP_misc_explobox,
  SP_misc_gib_arm,
  SP_misc_gib_head,
  SP_misc_gib_leg,
  SP_misc_satellite_dish,
  SP_misc_strogg_ship,
  SP_misc_teleporter,
  SP_misc_teleporter_dest,
  SP_misc_viper,
  SP_misc_viper_bomb,
  SP_path_corner,
  SP_point_combat,
  SP_target_character,
  SP_target_string,
  SP_viewthing,
  SP_monster_commander_body,
  BecomeExplosion1,
  BecomeExplosion2,
  ThrowDebris,
  ThrowGib,
  ThrowHead,
  barrel_delay,
  barrel_explode,
  barrel_touch,
  commander_body_drop,
  commander_body_think,
  commander_body_use,
  func_clock_format_countdown,
  func_clock_reset,
  func_clock_think,
  func_clock_use,
  func_explosive_explode,
  func_explosive_spawn,
  func_explosive_use,
  gib_die,
  gib_think,
  gib_touch,
  misc_banner_think,
  misc_blackhole_think,
  misc_blackhole_use,
  misc_deadsoldier_die,
  misc_easterchick2_think,
  misc_easterchick_think,
  misc_eastertank_think,
  misc_satellite_dish_think,
  misc_satellite_dish_use,
  misc_strogg_ship_use,
  misc_viper_bomb_prethink,
  misc_viper_bomb_touch,
  misc_viper_bomb_use,
  misc_viper_use,
  path_corner_touch,
  point_combat_touch,
  target_string_use,
  teleporter_touch,
  TH_viewthing,
  Use_Areaportal
} from "./g_misc.js";

export {
  AnglesNormalize,
  SnapToEights,
  SP_turret_base,
  SP_turret_breach,
  SP_turret_driver,
  turret_blocked,
  turret_breach_fire,
  turret_breach_finish_init,
  turret_breach_think,
  turret_driver_die,
  turret_driver_link,
  turret_driver_think
} from "./g_turret.js";

export {
  AttackFinished,
  M_CatagorizePosition,
  M_CheckGround,
  M_droptofloor,
  M_FliesOff,
  M_FliesOn,
  M_FlyCheck,
  M_MoveFrame,
  M_SetEffects,
  M_WorldEffects,
  flymonster_start,
  flymonster_start_go,
  monster_death_use,
  monster_fire_bfg,
  monster_fire_blaster,
  monster_fire_bullet,
  monster_fire_grenade,
  monster_fire_railgun,
  monster_fire_rocket,
  monster_fire_shotgun,
  monster_start,
  monster_start_go,
  monster_think,
  monster_triggered_spawn,
  monster_triggered_spawn_use,
  monster_triggered_start,
  monster_use,
  swimmonster_start,
  swimmonster_start_go,
  walkmonster_start,
  walkmonster_start_go
} from "./g_monster.js";

export {
  DI_NODIR,
  STEPSIZE,
  M_ChangeYaw,
  M_CheckBottom,
  M_MoveToGoal,
  M_walkmove,
  SV_CloseEnough,
  SV_FixCheckBottom,
  SV_NewChaseDir,
  SV_StepDirection,
  SV_movestep
} from "./m_move.js";

export {
  G_RunEntity,
  G_RunFrame,
  SV_Impact,
  SV_Physics_None,
  SV_Physics_Pusher,
  SV_Push,
  SV_PushEntity,
  SV_RunThink,
  SV_TestEntityPosition,
  runGameFrames
} from "./g_phys.js";

export {
  MAX_IPFILTERS,
  SV_FilterPacket,
  SVCmd_AddIP_f,
  SVCmd_ListIP_f,
  SVCmd_RemoveIP_f,
  SVCmd_WriteIP_f,
  ServerCommand,
  StringToFilter,
  Svcmd_Test_f,
  createGameServerCommandState
} from "./g_svcmds.js";

export {
  ClientEndServerFrames,
  ClientCommand as GameMainClientCommand,
  CheckDMRules,
  CreateTargetChangeLevel,
  EndDMLevel,
  ExitLevel,
  G_RunFrame as G_MainRunFrame,
  GetGameApi as GetGameApiFunction,
  InitGame,
  ReadGame,
  ReadLevel,
  ShutdownGame,
  WriteGame,
  WriteLevel,
  createGameMainContext
} from "./g_main.js";

export {
  clientfields,
  findGameSaveFunction,
  findGameSaveMove,
  fields as gameSaveFields,
  levelfields,
  mmove_reloc,
  registerGameSaveFunction,
  registerGameSaveFunctions,
  registerGameSaveMove,
  registerGameSaveMoves
} from "./g_save.js";

export {
  SP_monster_berserk,
  berserk_attack_club,
  berserk_attack_spike,
  berserk_dead,
  berserk_die,
  berserk_fidget,
  berserk_melee,
  berserk_move_attack_club,
  berserk_move_attack_spike,
  berserk_move_attack_strike,
  berserk_move_death1,
  berserk_move_death2,
  berserk_move_pain1,
  berserk_move_pain2,
  berserk_move_run1,
  berserk_move_stand,
  berserk_move_stand_fidget,
  berserk_move_walk,
  berserk_pain,
  berserk_run,
  berserk_search,
  berserk_sight,
  berserk_stand,
  berserk_strike,
  berserk_swing,
  berserk_walk
} from "./m_berserk.js";

export {
  Boss2MachineGun,
  Boss2Rocket,
  Boss2_CheckAttack,
  MZ2_BOSS2_MACHINEGUN_L1,
  MZ2_BOSS2_MACHINEGUN_R1,
  MZ2_BOSS2_ROCKET_1,
  MZ2_BOSS2_ROCKET_2,
  MZ2_BOSS2_ROCKET_3,
  MZ2_BOSS2_ROCKET_4,
  SP_monster_boss2,
  boss2_attack,
  boss2_attack_mg,
  boss2_dead,
  boss2_die,
  boss2_firebullet_left,
  boss2_firebullet_right,
  boss2_move_attack_mg,
  boss2_move_attack_post_mg,
  boss2_move_attack_pre_mg,
  boss2_move_attack_rocket,
  boss2_move_death,
  boss2_move_pain_heavy,
  boss2_move_pain_light,
  boss2_move_run,
  boss2_move_stand,
  boss2_move_walk,
  boss2_pain,
  boss2_reattack_mg,
  boss2_run,
  boss2_search,
  boss2_stand,
  boss2_walk
} from "./m_boss2.js";

export {
  SP_monster_boss3_stand,
  Think_Boss3Stand,
  Use_Boss3
} from "./m_boss3.js";

export {
  Jorg_CheckAttack,
  MZ2_JORG_BFG_1,
  MZ2_JORG_MACHINEGUN_L1,
  MZ2_JORG_MACHINEGUN_L2,
  MZ2_JORG_MACHINEGUN_L3,
  MZ2_JORG_MACHINEGUN_L4,
  MZ2_JORG_MACHINEGUN_L5,
  MZ2_JORG_MACHINEGUN_L6,
  MZ2_JORG_MACHINEGUN_R1,
  MZ2_JORG_MACHINEGUN_R2,
  MZ2_JORG_MACHINEGUN_R3,
  MZ2_JORG_MACHINEGUN_R4,
  MZ2_JORG_MACHINEGUN_R5,
  MZ2_JORG_MACHINEGUN_R6,
  SP_monster_jorg,
  jorgBFG,
  jorgMachineGun,
  jorg_attack,
  jorg_attack1,
  jorg_dead,
  jorg_die,
  jorg_firebullet,
  jorg_firebullet_left,
  jorg_firebullet_right,
  jorg_idle,
  jorg_move_attack1,
  jorg_move_attack2,
  jorg_move_death,
  jorg_move_end_attack1,
  jorg_move_end_walk,
  jorg_move_pain1,
  jorg_move_pain2,
  jorg_move_pain3,
  jorg_move_run,
  jorg_move_stand,
  jorg_move_start_attack1,
  jorg_move_start_walk,
  jorg_move_walk,
  jorg_pain,
  jorg_reattack1,
  jorg_run,
  jorg_search,
  jorg_stand,
  jorg_walk
} from "./m_boss31.js";

export {
  MakronHyperblaster,
  MakronPrecache,
  MakronRailgun,
  MakronSaveloc,
  MakronSpawn,
  MakronToss,
  Makron_CheckAttack,
  MZ2_MAKRON_BFG,
  MZ2_MAKRON_BLASTER_1,
  MZ2_MAKRON_BLASTER_2,
  MZ2_MAKRON_BLASTER_3,
  MZ2_MAKRON_BLASTER_4,
  MZ2_MAKRON_BLASTER_5,
  MZ2_MAKRON_BLASTER_6,
  MZ2_MAKRON_BLASTER_7,
  MZ2_MAKRON_BLASTER_8,
  MZ2_MAKRON_BLASTER_9,
  MZ2_MAKRON_BLASTER_10,
  MZ2_MAKRON_BLASTER_11,
  MZ2_MAKRON_BLASTER_12,
  MZ2_MAKRON_BLASTER_13,
  MZ2_MAKRON_BLASTER_14,
  MZ2_MAKRON_BLASTER_15,
  MZ2_MAKRON_BLASTER_16,
  MZ2_MAKRON_BLASTER_17,
  MZ2_MAKRON_RAILGUN_1,
  SP_monster_makron,
  makronBFG,
  makron_attack,
  makron_brainsplorch,
  makron_dead,
  makron_die,
  makron_hit,
  makron_move_attack3,
  makron_move_attack4,
  makron_move_attack5,
  makron_move_death2,
  makron_move_death3,
  makron_move_pain4,
  makron_move_pain5,
  makron_move_pain6,
  makron_move_run,
  makron_move_sight,
  makron_move_stand,
  makron_move_walk,
  makron_pain,
  makron_popup,
  makron_prerailgun,
  makron_run,
  makron_sight,
  makron_stand,
  makron_step_left,
  makron_step_right,
  makron_taunt,
  makron_torso,
  makron_torso_think,
  makron_walk
} from "./m_boss32.js";

export {
  SP_monster_brain,
  brain_chest_closed,
  brain_chest_open,
  brain_dead,
  brain_die,
  brain_dodge,
  brain_duck_down,
  brain_duck_hold,
  brain_duck_up,
  brain_hit_left,
  brain_hit_right,
  brain_idle,
  brain_melee,
  brain_move_attack1,
  brain_move_attack2,
  brain_move_death1,
  brain_move_death2,
  brain_move_defense,
  brain_move_duck,
  brain_move_idle,
  brain_move_pain1,
  brain_move_pain2,
  brain_move_pain3,
  brain_move_run,
  brain_move_stand,
  brain_move_walk1,
  brain_pain,
  brain_run,
  brain_search,
  brain_sight,
  brain_stand,
  brain_swing_left,
  brain_swing_right,
  brain_tentacle_attack,
  brain_walk
} from "./m_brain.js";

export {
  ChickMoan,
  ChickReload,
  ChickRocket,
  ChickSlash,
  Chick_PreAttack1,
  MZ2_CHICK_ROCKET_1,
  SP_monster_chick,
  chick_attack,
  chick_attack1,
  chick_dead,
  chick_die,
  chick_dodge,
  chick_duck_down,
  chick_duck_hold,
  chick_duck_up,
  chick_fidget,
  chick_melee,
  chick_move_attack1,
  chick_move_death1,
  chick_move_death2,
  chick_move_duck,
  chick_move_end_attack1,
  chick_move_end_slash,
  chick_move_fidget,
  chick_move_pain1,
  chick_move_pain2,
  chick_move_pain3,
  chick_move_run,
  chick_move_slash,
  chick_move_stand,
  chick_move_start_attack1,
  chick_move_start_run,
  chick_move_start_slash,
  chick_move_walk,
  chick_pain,
  chick_rerocket,
  chick_reslash,
  chick_run,
  chick_sight,
  chick_slash,
  chick_stand,
  chick_walk
} from "./m_chick.js";

export {
  SP_monster_flipper,
  flipper_bite,
  flipper_dead,
  flipper_die,
  flipper_melee,
  flipper_move_attack,
  flipper_move_death,
  flipper_move_pain1,
  flipper_move_pain2,
  flipper_move_run_loop,
  flipper_move_run_start,
  flipper_move_stand,
  flipper_move_start_run,
  flipper_move_walk,
  flipper_pain,
  flipper_preattack,
  flipper_run,
  flipper_run_loop,
  flipper_sight,
  flipper_stand,
  flipper_start_run,
  flipper_walk
} from "./m_flipper.js";

export {
  MZ2_FLOAT_BLASTER_1,
  SP_monster_floater,
  floater_attack,
  floater_dead,
  floater_die,
  floater_fire_blaster,
  floater_idle,
  floater_melee,
  floater_move_activate,
  floater_move_attack1,
  floater_move_attack2,
  floater_move_attack3,
  floater_move_death,
  floater_move_pain1,
  floater_move_pain2,
  floater_move_pain3,
  floater_move_run,
  floater_move_stand1,
  floater_move_stand2,
  floater_move_walk,
  floater_pain,
  floater_run,
  floater_sight,
  floater_stand,
  floater_walk,
  floater_wham,
  floater_zap
} from "./m_float.js";

export {
  MZ2_FLYER_BLASTER_1,
  MZ2_FLYER_BLASTER_2,
  SP_monster_flyer,
  flyer_attack,
  flyer_check_melee,
  flyer_die,
  flyer_fire,
  flyer_fireleft,
  flyer_fireright,
  flyer_idle,
  flyer_melee,
  flyer_move_attack2,
  flyer_move_bankleft,
  flyer_move_bankright,
  flyer_move_defense,
  flyer_move_end_melee,
  flyer_move_loop_melee,
  flyer_move_pain1,
  flyer_move_pain2,
  flyer_move_pain3,
  flyer_move_rollleft,
  flyer_move_rollright,
  flyer_move_run,
  flyer_move_stand,
  flyer_move_start,
  flyer_move_start_melee,
  flyer_move_stop,
  flyer_move_walk,
  flyer_nextmove,
  flyer_pain,
  flyer_pop_blades,
  flyer_run,
  flyer_setstart,
  flyer_sight,
  flyer_slash_left,
  flyer_slash_right,
  flyer_stand,
  flyer_start,
  flyer_stop,
  flyer_walk
} from "./m_flyer.js";

export {
  GaldiatorMelee,
  GladiatorGun,
  MZ2_GLADIATOR_RAILGUN_1,
  SP_monster_gladiator,
  gladiator_attack,
  gladiator_cleaver_swing,
  gladiator_dead,
  gladiator_die,
  gladiator_idle,
  gladiator_melee,
  gladiator_move_attack_gun,
  gladiator_move_attack_melee,
  gladiator_move_death,
  gladiator_move_pain,
  gladiator_move_pain_air,
  gladiator_move_run,
  gladiator_move_stand,
  gladiator_move_walk,
  gladiator_pain,
  gladiator_run,
  gladiator_search,
  gladiator_sight,
  gladiator_stand,
  gladiator_walk
} from "./m_gladiator.js";

export {
  InfantryMachineGun,
  MZ2_INFANTRY_MACHINEGUN_1,
  MZ2_INFANTRY_MACHINEGUN_2,
  MZ2_INFANTRY_MACHINEGUN_3,
  MZ2_INFANTRY_MACHINEGUN_4,
  MZ2_INFANTRY_MACHINEGUN_5,
  MZ2_INFANTRY_MACHINEGUN_6,
  MZ2_INFANTRY_MACHINEGUN_7,
  MZ2_INFANTRY_MACHINEGUN_8,
  MZ2_INFANTRY_MACHINEGUN_9,
  MZ2_INFANTRY_MACHINEGUN_10,
  MZ2_INFANTRY_MACHINEGUN_11,
  MZ2_INFANTRY_MACHINEGUN_12,
  MZ2_INFANTRY_MACHINEGUN_13,
  SP_monster_infantry,
  infantry_attack,
  infantry_cock_gun,
  infantry_dead,
  infantry_die,
  infantry_dodge,
  infantry_duck_down,
  infantry_duck_hold,
  infantry_duck_up,
  infantry_fidget,
  infantry_fire,
  infantry_move_attack1,
  infantry_move_attack2,
  infantry_move_death1,
  infantry_move_death2,
  infantry_move_death3,
  infantry_move_duck,
  infantry_move_fidget,
  infantry_move_pain1,
  infantry_move_pain2,
  infantry_move_run,
  infantry_move_stand,
  infantry_move_walk,
  infantry_pain,
  infantry_run,
  infantry_sight,
  infantry_smack,
  infantry_stand,
  infantry_swing,
  infantry_walk
} from "./m_infantry.js";

export {
  MZ2_MEDIC_BLASTER_1,
  SP_monster_medic,
  medic_FindDeadMonster,
  medic_attack,
  medic_cable_attack,
  medic_checkattack,
  medic_continue,
  medic_dead,
  medic_die,
  medic_dodge,
  medic_duck_down,
  medic_duck_hold,
  medic_duck_up,
  medic_fire_blaster,
  medic_hook_launch,
  medic_hook_retract,
  medic_idle,
  medic_move_attackBlaster,
  medic_move_attackCable,
  medic_move_attackHyperBlaster,
  medic_move_death,
  medic_move_duck,
  medic_move_pain1,
  medic_move_pain2,
  medic_move_run,
  medic_move_stand,
  medic_move_walk,
  medic_pain,
  medic_run,
  medic_search,
  medic_sight,
  medic_stand,
  medic_walk
} from "./m_medic.js";

export {
  SP_monster_mutant,
  mutant_check_jump,
  mutant_check_landing,
  mutant_check_melee,
  mutant_check_refire,
  mutant_checkattack,
  mutant_dead,
  mutant_die,
  mutant_hit_left,
  mutant_hit_right,
  mutant_idle,
  mutant_idle_loop,
  mutant_jump,
  mutant_jump_takeoff,
  mutant_jump_touch,
  mutant_melee,
  mutant_move_attack,
  mutant_move_death1,
  mutant_move_death2,
  mutant_move_idle,
  mutant_move_jump,
  mutant_move_pain1,
  mutant_move_pain2,
  mutant_move_pain3,
  mutant_move_run,
  mutant_move_stand,
  mutant_move_start_walk,
  mutant_move_walk,
  mutant_pain,
  mutant_run,
  mutant_search,
  mutant_sight,
  mutant_stand,
  mutant_step,
  mutant_swing,
  mutant_walk,
  mutant_walk_loop
} from "./m_mutant.js";

export {
  GunnerFire,
  GunnerGrenade,
  MZ2_GUNNER_GRENADE_1,
  MZ2_GUNNER_GRENADE_2,
  MZ2_GUNNER_GRENADE_3,
  MZ2_GUNNER_GRENADE_4,
  MZ2_GUNNER_MACHINEGUN_1,
  MZ2_GUNNER_MACHINEGUN_2,
  MZ2_GUNNER_MACHINEGUN_3,
  MZ2_GUNNER_MACHINEGUN_4,
  MZ2_GUNNER_MACHINEGUN_5,
  MZ2_GUNNER_MACHINEGUN_6,
  MZ2_GUNNER_MACHINEGUN_7,
  MZ2_GUNNER_MACHINEGUN_8,
  SP_monster_gunner,
  gunner_attack,
  gunner_dead,
  gunner_die,
  gunner_dodge,
  gunner_duck_down,
  gunner_duck_hold,
  gunner_duck_up,
  gunner_fidget,
  gunner_fire_chain,
  gunner_idlesound,
  gunner_move_attack_chain,
  gunner_move_attack_grenade,
  gunner_move_death,
  gunner_move_duck,
  gunner_move_endfire_chain,
  gunner_move_fidget,
  gunner_move_fire_chain,
  gunner_move_pain1,
  gunner_move_pain2,
  gunner_move_pain3,
  gunner_move_run,
  gunner_move_runandshoot,
  gunner_move_stand,
  gunner_move_walk,
  gunner_opengun,
  gunner_pain,
  gunner_refire_chain,
  gunner_run,
  gunner_runandshoot,
  gunner_search,
  gunner_sight,
  gunner_stand,
  gunner_walk
} from "./m_gunner.js";

export {
  BossExplode,
  MZ2_SUPERTANK_MACHINEGUN_1,
  MZ2_SUPERTANK_MACHINEGUN_2,
  MZ2_SUPERTANK_MACHINEGUN_3,
  MZ2_SUPERTANK_MACHINEGUN_4,
  MZ2_SUPERTANK_MACHINEGUN_5,
  MZ2_SUPERTANK_MACHINEGUN_6,
  MZ2_SUPERTANK_ROCKET_1,
  MZ2_SUPERTANK_ROCKET_2,
  MZ2_SUPERTANK_ROCKET_3,
  SP_monster_supertank,
  TreadSound,
  supertankMachineGun,
  supertankRocket,
  supertank_attack,
  supertank_dead,
  supertank_die,
  supertank_forward,
  supertank_move_attack1,
  supertank_move_attack2,
  supertank_move_attack3,
  supertank_move_attack4,
  supertank_move_backward,
  supertank_move_death,
  supertank_move_end_attack1,
  supertank_move_forward,
  supertank_move_pain1,
  supertank_move_pain2,
  supertank_move_pain3,
  supertank_move_run,
  supertank_move_stand,
  supertank_move_turn_left,
  supertank_move_turn_right,
  supertank_pain,
  supertank_reattack1,
  supertank_run,
  supertank_search,
  supertank_stand,
  supertank_walk
} from "./m_supertank.js";

export {
  MZ2_TANK_BLASTER_1,
  MZ2_TANK_BLASTER_2,
  MZ2_TANK_BLASTER_3,
  MZ2_TANK_MACHINEGUN_1,
  MZ2_TANK_ROCKET_1,
  MZ2_TANK_ROCKET_2,
  MZ2_TANK_ROCKET_3,
  SP_monster_tank,
  TankBlaster,
  TankMachineGun,
  TankRocket,
  TankStrike,
  tank_attack,
  tank_dead,
  tank_die,
  tank_doattack_rocket,
  tank_footstep,
  tank_idle,
  tank_move_attack_blast,
  tank_move_attack_chain,
  tank_move_attack_fire_rocket,
  tank_move_attack_post_blast,
  tank_move_attack_post_rocket,
  tank_move_attack_pre_rocket,
  tank_move_attack_strike,
  tank_move_death,
  tank_move_pain1,
  tank_move_pain2,
  tank_move_pain3,
  tank_move_reattack_blast,
  tank_move_run,
  tank_move_stand,
  tank_move_start_run,
  tank_move_walk,
  tank_pain,
  tank_poststrike,
  tank_reattack_blaster,
  tank_refire_rocket,
  tank_run,
  tank_sight,
  tank_stand,
  tank_thud,
  tank_walk,
  tank_windup
} from "./m_tank.js";

export {
  MZ2_HOVER_BLASTER_1,
  SP_monster_hover,
  hover_attack,
  hover_dead,
  hover_deadthink,
  hover_die,
  hover_fire_blaster,
  hover_move_attack1,
  hover_move_backward,
  hover_move_death1,
  hover_move_end_attack,
  hover_move_forward,
  hover_move_land,
  hover_move_pain1,
  hover_move_pain2,
  hover_move_pain3,
  hover_move_run,
  hover_move_stand,
  hover_move_start_attack,
  hover_move_stop1,
  hover_move_stop2,
  hover_move_takeoff,
  hover_move_walk,
  hover_pain,
  hover_reattack,
  hover_run,
  hover_search,
  hover_sight,
  hover_stand,
  hover_start_attack,
  hover_walk
} from "./m_hover.js";

export {
  SP_monster_parasite,
  parasite_attack,
  parasite_dead,
  parasite_die,
  parasite_do_fidget,
  parasite_drain_attack,
  parasite_drain_attack_ok,
  parasite_end_fidget,
  parasite_idle,
  parasite_launch,
  parasite_move_break,
  parasite_move_death,
  parasite_move_drain,
  parasite_move_end_fidget,
  parasite_move_fidget,
  parasite_move_pain1,
  parasite_move_run,
  parasite_move_stand,
  parasite_move_start_fidget,
  parasite_move_start_run,
  parasite_move_start_walk,
  parasite_move_stop_run,
  parasite_move_stop_walk,
  parasite_move_walk,
  parasite_pain,
  parasite_reel_in,
  parasite_refidget,
  parasite_run,
  parasite_scratch,
  parasite_search,
  parasite_sight,
  parasite_stand,
  parasite_start_run,
  parasite_start_walk,
  parasite_tap,
  parasite_walk
} from "./m_parasite.js";

export {
  SP_misc_insane,
  insane_checkdown,
  insane_checkup,
  insane_cross,
  insane_dead,
  insane_die,
  insane_fist,
  insane_moan,
  insane_move_crawl,
  insane_move_crawl_death,
  insane_move_crawl_pain,
  insane_move_cross,
  insane_move_down,
  insane_move_downtoup,
  insane_move_jumpdown,
  insane_move_run_insane,
  insane_move_run_normal,
  insane_move_runcrawl,
  insane_move_stand_death,
  insane_move_stand_insane,
  insane_move_stand_normal,
  insane_move_stand_pain,
  insane_move_struggle_cross,
  insane_move_uptodown,
  insane_move_walk_insane,
  insane_move_walk_normal,
  insane_onground,
  insane_pain,
  insane_run,
  insane_scream,
  insane_shake,
  insane_stand,
  insane_walk
} from "./m_insane.js";

export {
  SP_func_button,
  SP_func_conveyor,
  SP_func_door,
  SP_func_door_rotating,
  SP_func_door_secret,
  SP_func_killbox,
  AngleMove_Begin,
  AngleMove_Calc,
  AngleMove_Done,
  AngleMove_Final,
  Move_Begin,
  Move_Calc,
  Move_Done,
  Move_Final,
  Think_CalcMoveSpeed,
  Think_AccelMove,
  Think_SpawnDoorTrigger,
  Touch_DoorTrigger,
  Touch_Plat_Center,
  SP_func_rotating,
  SP_func_timer,
  SP_func_train,
  SP_func_water,
  SP_trigger_elevator,
  door_blocked,
  door_go_down,
  door_go_up,
  door_hit_bottom,
  door_hit_top,
  door_killed,
  door_touch,
  door_use,
  door_use_areaportals,
  Use_Plat,
  SP_func_plat,
  plat_blocked,
  plat_go_down,
  plat_go_up,
  plat_hit_bottom,
  plat_hit_top,
  plat_spawn_inside_trigger,
  button_fire,
  button_killed,
  button_touch,
  button_use,
  func_conveyor_use,
  func_timer_think,
  func_timer_use,
  func_train_find,
  rotating_use,
  train_next,
  train_resume,
  train_use,
  trigger_elevator_init,
  trigger_elevator_use,
  use_killbox
} from "./g_func.js";

export {
  InitTrigger,
  SP_trigger_always,
  SP_trigger_counter,
  SP_trigger_gravity,
  SP_trigger_hurt,
  SP_trigger_key,
  SP_trigger_monsterjump,
  SP_trigger_multiple,
  SP_trigger_once,
  SP_trigger_push,
  SP_trigger_relay,
  Touch_Multi,
  Use_Multi,
  hurt_touch,
  hurt_use,
  multi_trigger,
  trigger_counter_use,
  trigger_enable,
  trigger_gravity_touch,
  trigger_key_use,
  trigger_monsterjump_touch,
  trigger_push_touch,
  trigger_relay_use
} from "./g_trigger.js";

export {
  SP_target_blaster,
  SP_target_changelevel,
  SP_target_crosslevel_target,
  SP_target_crosslevel_trigger,
  SP_target_earthquake,
  SP_target_explosion,
  SP_target_goal,
  SP_target_help,
  SP_target_laser,
  SP_target_lightramp,
  SP_target_secret,
  SP_target_speaker,
  SP_target_spawner,
  SP_target_splash,
  SP_target_temp_entity,
  Use_Target_Help,
  Use_Target_Speaker,
  Use_Target_Tent,
  target_crosslevel_target_think,
  target_earthquake_think,
  target_earthquake_use,
  target_explosion_explode,
  target_laser_off,
  target_laser_on,
  target_laser_start,
  target_laser_think,
  target_laser_use,
  target_lightramp_think,
  target_lightramp_use,
  trigger_crosslevel_trigger_use,
  use_target_blaster,
  use_target_changelevel,
  use_target_explosion,
  use_target_goal,
  use_target_secret,
  use_target_spawner,
  use_target_splash
} from "./g_target.js";

export {
  Grenade_Explode,
  Grenade_Touch,
  bfg_explode,
  bfg_think,
  bfg_touch,
  blaster_touch,
  fire_bfg,
  fire_blaster,
  fire_bullet,
  fire_hit,
  fire_grenade,
  fire_grenade2,
  fire_rail,
  fire_rocket,
  fire_shotgun,
  rocket_touch
} from "./g_weapon.js";

export {
  BeginIntermission,
  Cmd_Help_f,
  Cmd_Score_f,
  DeathmatchScoreboard,
  DeathmatchScoreboardMessage,
  G_CheckChaseStats,
  G_SetSpectatorStats,
  G_SetStats,
  HelpComputer,
  MoveClientToIntermission
} from "./p_hud.js";

export {
  ClientEndServerFrame,
  G_SetClientEffects,
  G_SetClientEvent,
  G_SetClientFrame,
  G_SetClientSound,
  P_DamageFeedback,
  P_FallingDamage,
  P_WorldEffects,
  SV_AddBlend,
  SV_CalcBlend,
  SV_CalcGunOffset,
  SV_CalcViewOffset,
  SV_CalcRoll,
  createPlayerViewFrameState
} from "./p_view.js";

export {
  CheckBlock,
  CopyToBodyQue,
  ClientBegin,
  ClientBeginDeathmatch,
  ClientBeginServerFrame,
  ClientConnect,
  ClientDisconnect,
  ClientObituary,
  FetchClientEntData,
  InitBodyQue,
  InitClientPersistant,
  InitClientResp,
  IsFemale,
  IsNeutral,
  ClientThink,
  ClientUserinfoChanged,
  LookAtKiller,
  PM_trace,
  PMpointcontents,
  PrintPmove,
  PlayersRangeFromSpot,
  PutClientInServer,
  SaveClientData,
  SP_CreateCoopSpots,
  SP_FixCoopSpots,
  SP_info_player_coop,
  SP_info_player_deathmatch,
  SP_info_player_intermission,
  SP_info_player_start,
  SelectCoopSpawnPoint,
  SelectDeathmatchSpawnPoint,
  SelectFarthestDeathmatchSpawnPoint,
  SelectRandomDeathmatchSpawnPoint,
  SelectSpawnPoint,
  TossClientWeapon,
  body_die,
  player_pain,
  player_die,
  respawn,
  spectator_respawn,
  UpdateChaseFollowers
} from "./p_client.js";

export type { GameWeaponWorldHooks } from "./g_weapon.js";
export type { GameMonsterHooks } from "./g_monster.js";
export type { GameServerCommandContext, GameServerCommandState, ipfilter_t } from "./g_svcmds.js";
export type { GameMainContext, GameMainContextOptions, GameMainCvars, GameMainHooks } from "./g_main.js";

export {
  G_TouchSolids,
  G_TouchTriggers,
  touchTriggerEntities
} from "./touch.js";

export {
  createLocalGameplayPlayer,
  LOCAL_GAME_WEAPON_HOOKS,
  LOCAL_WEAPON_SLOTS,
  buildLocalWeaponBootstrapData,
  refillLocalDemoInventory,
  seedLocalWeaponInventory,
  selectLocalDemoWeapon,
  selectLocalWeapon,
  thinkLocalWeapon
} from "./local-game-bootstrap.js";

export {
  Blaster_Fire,
  Chaingun_Fire,
  ChangeWeapon,
  Drop_Weapon,
  Machinegun_Fire,
  NoAmmoWeaponChange,
  P_ProjectSource,
  Pickup_Weapon,
  PlayerNoise,
  Think_Weapon,
  Use_Weapon,
  Weapon_BFG,
  Weapon_Blaster,
  Weapon_Blaster_Fire,
  Weapon_Chaingun,
  Weapon_Generic,
  Weapon_Grenade,
  Weapon_GrenadeLauncher,
  Weapon_HyperBlaster,
  Weapon_HyperBlaster_Fire,
  Weapon_Machinegun,
  Weapon_Railgun,
  Weapon_RocketLauncher,
  Weapon_Shotgun,
  Weapon_SuperShotgun,
  Weapon_RocketLauncher_Fire,
  weapon_bfg_fire,
  weapon_grenade_fire,
  weapon_grenadelauncher_fire,
  weapon_railgun_fire,
  weapon_shotgun_fire,
  weapon_supershotgun_fire
} from "./p_weapon.js";

export {
  PlayerTrail_Add,
  PlayerTrail_Init,
  PlayerTrail_LastSpot,
  PlayerTrail_New,
  PlayerTrail_PickFirst,
  PlayerTrail_PickNext,
  TRAIL_LENGTH
} from "./p_trail.js";

export type {
  GameItemArmorInfo,
  GameItemDefinition,
  GameItemDropKind,
  GameItemPickupKind,
  GameItemUseKind,
  GameItemWeaponThinkKind
} from "./g_items.js";

export type {
  GameEntity,
  GameEntityBlocked,
  GameEntityFieldName,
  GameEntityKind,
  GameEntityDie,
  GameEntityThink,
  GameAssetRegistry,
  GameCenterprintEvent,
  GameCollisionBridge,
  GameConfigstringUpdate,
  GameCprintfEvent,
  GameSoundEvent,
  GameTempEntityEvent,
  GameMoveInfo,
  GameMonsterMuzzleFlashEvent,
  GamePlayerMuzzleFlashEvent,
  GameEntityTouch,
  GameEntityUse,
  GameRuntime,
  GameRuntimeLogEntry
} from "./runtime.js";

export type {
  client_persistant_t,
  client_respawn_t,
  field_t,
  game_locals_t,
  gitem_armor_t,
  gitem_t,
  level_locals_t,
  mframe_t,
  mmove_t,
  monsterinfo_t,
  spawn_temp_t
} from "./g_local.js";

export type { GameWeaponHooks } from "./p_weapon.js";
export type { GameCommandContext, GameCommandCvars, GameCommandHooks } from "./g_cmds.js";
export type {
  LocalInventoryGrant,
  LocalItemStringEntry,
  LocalWeaponBootstrapData,
  LocalWeaponSlotKey
} from "./local-game-bootstrap.js";
