FROM nginx:latest

COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copy all applicable directories
COPY ./dist /usr/app/dist

# Make port 80 available to the world outside this container
EXPOSE 80

# Define environment variable
# ENV NAME World

CMD ["nginx", "-g", "daemon off;"]
