/**
 * File: q_shared.ts
 * Purpose: Expose the Three.js rendering bridge helpers for Quake II runtime data.
 *
 * This file is not a direct source port.
 * It is a package entry point for the Three.js backend package.
 *
 * Dependencies:
 * - packages/renderer-three/src/ref-gl-host.ts
 * - packages/renderer-three/src/gl-world-scene-adapter.ts
 */

export { createThreeGlWorldSceneAdapter } from "./gl-world-scene-adapter.js";
export { createQuakeSkyResolver } from "./quake-sky-resolver.js";
export { createThreeSkySceneAdapter } from "./sky-scene-adapter.js";
export { createThreeRefreshEntitySync } from "./refresh-entity-sync.js";
export { createThreeParticleSync } from "./particle-sync.js";
export { createRefGlBootstrap } from "./ref-gl-bootstrap.js";
export { createRefGlHost } from "./ref-gl-host.js";
export {
  GL_DrawAliasShadow,
  R_CullAliasModel,
  aliasEntityHasShell,
  type AliasCullEntityState,
  buildAliasShellShadeLight,
  buildAliasShadeVector,
  buildAliasVertexColors,
  computeAliasShadeLight,
  computeAliasWeaponLightLevel,
  getAliasShadedotsForYaw,
  NUMVERTEXNORMALS,
  sanitizeAliasFramePair
} from "./gl_mesh.js";
export {
  GL_DrawParticles,
  GL_DrawColoredStereoLinePair,
  GL_DrawStereoPattern,
  GL_BACK_LEFT,
  MYgluPerspective,
  R_BeginFrame,
  R_Clear,
  R_CullBox,
  R_DrawBeam,
  R_DrawEntitiesOnList,
  R_Flash,
  R_DrawNullModel,
  R_DrawParticles,
  R_PolyBlend,
  R_DrawSpriteModel,
  R_Init,
  R_Register,
  R_SetMode,
  R_Shutdown,
  GetRefAPI,
  R_RenderFrame,
  R_RenderView,
  R_RotateForEntity,
  R_SetGL2D,
  R_SetFrustum,
  R_SetLightLevel,
  R_SetPalette,
  R_SetupFrame,
  R_SetupGL,
  SignbitsForPlane,
  V_AddBlend,
  createGlRmainRuntime,
  setRmainCvars,
  setRmainPaletteTable,
  setRmainParticleTexture,
  setRmainVid,
  setRmainWorldModel
} from "./gl_rmain.js";
export {
  GL_ALPHA_TEST,
  GL_BLEND,
  GL_CULL_FACE,
  GL_DEPTH_TEST,
  GL_FILL,
  GL_FLAT,
  GL_FRONT,
  GL_FRONT_AND_BACK,
  GL_GREATER,
  GL_ONE_MINUS_SRC_ALPHA,
  GL_POINT_SMOOTH,
  GL_REPEAT,
  GL_RGB,
  GL_SRC_ALPHA,
  GL_TEXTURE_2D,
  GL_TEXTURE_MAG_FILTER,
  GL_TEXTURE_MIN_FILTER,
  GL_TEXTURE_WRAP_S,
  GL_TEXTURE_WRAP_T,
  GL_ScreenShot_f,
  GL_SetDefaultState,
  GL_Strings_f,
  GL_UpdateSwapInterval,
  R_InitParticleTexture,
  buildNoTextureRgba,
  buildParticleTextureRgba,
  buildTgaHeader,
  createGlRmiscRuntime,
  findScreenshotName,
  setRmiscCvars,
  syncRmiscExtensionStateFromRmain,
  setRmiscExtensionState,
  setRmiscGlConfig,
  setRmiscGlState,
  setRmiscImageRuntime,
  setRmiscVid,
  swapRgbToBgr
} from "./gl_rmisc.js";
export {
  BoundPoly,
  ClipSkyPolygon,
  DrawSkyPolygon,
  EmitWaterPolys,
  GL_SubdivideSurface,
  MakeSkyVec,
  MAX_CLIP_VERTS,
  ON_EPSILON,
  R_AddSkySurface,
  R_ClearSkyBox,
  R_DrawSkyBox,
  R_SetSky,
  SKY_CLIP,
  SKY_SUFFIXES,
  SKY_TEX_ORDER,
  ST_TO_VEC,
  SUBDIVIDE_SIZE,
  TURBSCALE,
  VEC_TO_ST,
  createGlWarpRuntime,
  getSkyTexClampBounds,
  setWarpFallbackTexture,
  setWarpHooks,
  setWarpModel,
  setWarpPaletteExtensionState,
  setWarpRefdefTime,
  setWarpSkyCvars,
  setWarpTurbulenceScale,
  setWarpViewOrigin
} from "./gl_warp.js";
export { r_turbsin } from "./warpsin.js";
export {
  DLIGHT_CUTOFF,
  R_AddDynamicLights,
  R_BuildLightMap,
  R_LightPoint,
  R_MarkLights,
  R_MarkModelLights,
  R_PushDlights,
  R_RenderDlight,
  R_RenderDlights,
  R_SetCacheState,
  RecursiveLightPoint,
  createGlLightRmainHooks,
  createGlLightRsurfHooks,
  createGlLightRuntime,
  setGlFlashblendEnabled,
  setGlLightCurrentEntity,
  setGlLightFrameCount,
  setGlLightRefdef,
  setGlLightViewVectors,
  setGlLightWorldModel,
  setGlModulate,
  setGlMonolightmapMode
} from "./gl_light.js";
export {
  BACKFACE_EPSILON,
  GL_RENDERER_3DFX,
  GL_RENDERER_3DLABS,
  GL_RENDERER_3DLABS_MISC,
  GL_RENDERER_3DPRO,
  GL_RENDERER_BANSHEE,
  GL_RENDERER_DYPIC,
  GL_RENDERER_GLINT_MX,
  GL_RENDERER_GLINT_TX,
  GL_RENDERER_IMPACT,
  GL_RENDERER_INTERGRAPH,
  GL_RENDERER_IR,
  GL_RENDERER_O2,
  GL_RENDERER_OTHER,
  GL_RENDERER_PCX1,
  GL_RENDERER_PCX2,
  GL_RENDERER_PERMEDIA2,
  GL_RENDERER_PMX,
  GL_RENDERER_POWERVR,
  GL_RENDERER_RE,
  GL_RENDERER_REAL3D,
  GL_RENDERER_REALIZM,
  GL_RENDERER_REALIZM2,
  GL_RENDERER_RIVA128,
  GL_RENDERER_SGI,
  GL_RENDERER_V1000,
  GL_RENDERER_V2100,
  GL_RENDERER_V2200,
  GL_RENDERER_VOODOO_RUSH,
  MAX_LBM_HEIGHT,
  PITCH,
  REF_VERSION,
  ROLL,
  YAW,
  createGlConfig,
  createGlLocalContext,
  createGlState,
  createGlVert,
  createRendererVidDef,
  hasValidFrustum,
  hasValidWorldMatrix,
  isGlImageNameWithinQPath,
  rserr_t
} from "./gl_local.js";
export {
  Draw_GetPalette,
  GL_Bind,
  GL_EnableMultitexture,
  GL_FindImage,
  GL_FreeUnusedImages,
  GL_ImageList_f,
  GL_InitImages,
  GL_LoadPic,
  GL_LoadWal,
  GL_LightScaleTexture,
  GL_MBind,
  GL_MipMap,
  GL_BuildPalettedTexture,
  GL_Upload8,
  GL_Upload32,
  GL_ResampleTexture,
  GL_RENDERER_VOODOO,
  GL_RENDERER_VOODOO2,
  GL_SelectTexture,
  GL_SetTexturePalette,
  GL_ShutdownImages,
  GL_TexEnv,
  GL_TextureAlphaMode,
  GL_TextureMode,
  GL_TextureSolidMode,
  LoadPCX,
  LoadTGA,
  MAX_GLTEXTURES,
  MAX_SCRAPS,
  R_FloodFillSkin,
  R_RegisterSkin,
  Scrap_AllocBlock,
  Scrap_Upload,
  TEXNUM_IMAGES,
  TEXNUM_LIGHTMAPS,
  TEXNUM_SCRAPS,
  createGlImage,
  createGlImageRuntime,
  imagetype_t,
  setDrawCharsImage,
  setRendererFlags as setImageRendererFlags,
  setIntensityValue,
  setNoBindEnabled,
  setPaletteExtensionState,
  setPicmipValue,
  setProtectedImages,
  setRoundDownEnabled,
  setVidGammaValue
} from "./gl_image.js";
export {
  Draw_Char,
  Draw_FadeScreen,
  Draw_Fill,
  Draw_FindPic,
  Draw_GetPicSize,
  Draw_InitLocal,
  Draw_Pic,
  Draw_StretchPic,
  Draw_StretchRaw,
  Draw_TileClear,
  GL_COLOR_INDEX,
  GL_COLOR_INDEX8_EXT,
  GL_RENDERER_MCD,
  GL_RENDERER_RENDITION,
  GL_RGBA,
  GL_UNSIGNED_BYTE,
  createGlDrawImage,
  createGlDrawRuntime,
  setColorTableExtensionEnabled,
  setGlTexSolidFormat,
  setPalette8to24,
  setRawPalette,
  setRendererFlags,
  setScrapDirty,
  setVidState
} from "./gl_draw.js";
export {
  GL_DISTANCE_ATTENUATION_EXT,
  GL_POINT_FADE_THRESHOLD_SIZE_EXT,
  GL_POINT_SIZE_MAX_EXT,
  GL_POINT_SIZE_MIN_EXT,
  GL_SHARED_TEXTURE_PALETTE_EXT,
  GL_TEXTURE0_SGIS,
  GL_TEXTURE1_SGIS,
  QGL_Init,
  QWGL_Init,
  createQglBootstrapHooks,
  QGL_PROCEDURES,
  QGL_OPTIONAL_PROCEDURES,
  QGL_REQUIRED_PROCEDURES,
  QGL_Shutdown,
  QWGL_Shutdown,
  QWGL_WIN32_PROCEDURES,
  createObjectQglProvider,
  createQglRuntime,
  createQwglRuntime,
  hasQglProcedure,
  hasQwglProcedure
} from "./qgl.js";
export { applyMd2AliasFrameLerp, applyMd2Frame, applyMd2LerpedFrame, buildMd2Mesh, loadMd2Model } from "./md2-mesh-builder.js";
export { createThreeBeamSync } from "./three-beam-sync.js";
export { createThreeDlightSync } from "./three-dlight-sync.js";
export { createThreeGlDrawAdapter } from "./three-gl-draw-adapter.js";
export { createThreePolyblendOverlay } from "./three-polyblend-overlay.js";
export {
  BLOCK_HEIGHT,
  BLOCK_WIDTH,
  DYNAMIC_LIGHT_HEIGHT,
  DYNAMIC_LIGHT_WIDTH,
  GL_LIGHTMAP_FORMAT,
  GL_BeginBuildingLightmaps,
  GL_BuildPolygonFromSurface,
  GL_CreateSurfaceLightmap,
  GL_EndBuildingLightmaps,
  GL_RenderLightmappedPoly,
  LIGHTMAP_BYTES,
  LM_AllocBlock,
  LM_InitBlock,
  LM_UploadBlock,
  MAX_LIGHTMAPS,
  DrawGLFlowingPoly,
  DrawGLPoly,
  DrawGLPolyChain,
  DrawGLWaterPoly,
  DrawGLWaterPolyLightmap,
  R_BlendLightmaps,
  R_DrawTriangleOutlines,
  R_TextureAnimation,
  createGlRsurfModelHooks,
  createGlRsurfRuntime,
  clearImageTextureChains,
  DrawTextureChains,
  R_DrawBrushModel,
  R_DrawInlineBModel,
  R_DrawWorld,
  R_MarkLeaves,
  R_RecursiveWorldNode,
  R_DrawAlphaSurfaces,
  R_RenderBrushPoly,
  setDynamicLightmapsEnabled,
  setCurrentEntity,
  setCurrentModel,
  setCurrentTime,
  setFrameCount,
  setFlashblendEnabled,
  setFullbrightEnabled,
  setLightmapOnly,
  setLightstyles,
  setMonolightmapMode,
  syncRsurfMultitextureFromRmain,
  setRefdefState,
  setShowTriangleOutlines,
  setMultitextureEnabled,
  setViewClusters,
  setViewOrigin,
  setWorldDrawFlags,
  setWorldModel,
  chainSurfaceByImage,
  queueAlphaSurface
} from "./gl_rsurf.js";
export { getAliasShadedot, getAliasShadedots, R_AVERTEXNORMAL_DOTS, SHADEDOT_NORMALS, SHADEDOT_QUANT } from "./anormtab.js";
export {
  CalcSurfaceExtents,
  Mod_Free,
  Mod_FreeAll,
  Mod_ClusterPVS,
  Mod_DecompressVis,
  Mod_ForName,
  Mod_Init,
  Mod_LoadEdges,
  Mod_LoadFaces,
  Mod_LoadLeafs,
  Mod_LoadLighting,
  Mod_LoadMarksurfaces,
  Mod_LoadNodes,
  Mod_LoadBrushModel,
  Mod_LoadAliasModel,
  Mod_LoadPlanes,
  Mod_LoadSpriteModel,
  Mod_LoadSubmodels,
  Mod_LoadSurfedges,
  Mod_LoadTexinfo,
  Mod_LoadVertexes,
  Mod_LoadVisibility,
  Mod_Modellist_f,
  Mod_PointInLeaf,
  Mod_SetParent,
  R_BeginRegistration,
  R_EndRegistration,
  R_RegisterModel,
  RadiusFromBounds,
  createGlModelRuntime,
  createRendererVisData
} from "./gl_model.js";
export {
  MAX_MD2SKINS,
  SIDE_BACK,
  SIDE_FRONT,
  SIDE_ON,
  SURF_DRAWBACKGROUND,
  SURF_DRAWSKY,
  SURF_DRAWTURB,
  SURF_PLANEBACK,
  SURF_UNDERWATER,
  VERTEXSIZE,
  createGlPoly,
  createMEdge,
  createMLeaf,
  createMModel,
  createMNode,
  createMSurface,
  createMTexinfo,
  createMVertex,
  createModel,
  getSurfaceStyleCapacity,
  hasSurfaceSamples,
  hasValidModelSkinCount,
  isModelNameWithinQPath,
  isValidGlPoly,
  modtype_t
} from "./gl_model.js";

export type { ThreeGlWorldSceneAdapter } from "./gl-world-scene-adapter.js";
export type { GlImage, GlImageHooks, GlImageRuntime, GlImageUploadResult, GlImageUploadSource } from "./gl_image.js";
export type { GlLightHooks, GlLightRuntime } from "./gl_light.js";
export type {
  GlRmainBeamSegment,
  GlRmainGlState,
  GlRmainHooks,
  GlRmainParticleTriangle,
  GlRmainProjection,
  GlRmainRuntime,
  GlRmainStereoLine,
  GlRmainStereoPattern,
  GlRmainSpriteVertex,
  GlRmainViewport
} from "./gl_rmain.js";
export type { GlRmiscHooks, GlRmiscRuntime, TargaHeader } from "./gl_rmisc.js";
export type { GlWarpRuntime, GlWarpSkyFace, GlWarpWaterPoly, GlWarpWaterVertex } from "./gl_warp.js";
export type {
  GL_DrawParticles_t,
  GL_BeginRenderingResult,
  GL_BeginRendering_t,
  GL_EndRendering_t,
  GlLocalContext,
  GlimpSetModeResult,
  GlimpHooks,
  R_MarkLights_t,
  R_SwapBuffers_t,
  R_TranslatePlayerSkin_t,
  SurfaceVoidCallback,
  WaterWarpPolyVerts_t,
  glconfig_t,
  glstate_t,
  glvert_t,
  viddef_t
} from "./gl_local.js";
export type { GlDrawHooks, GlDrawImage, GlDrawQuad, GlDrawRawUpload, GlDrawRuntime } from "./gl_draw.js";
export type { GlLightmapState, GlRsurfEntityRef, GlRsurfHooks, GlRsurfLightstyle, GlRsurfRuntime } from "./gl_rsurf.js";
export type {
  QglDispatchTable,
  QglBootstrapOptions,
  QglInitOptions,
  QglInventoryProcedure,
  QglOptionalProcedure,
  QglProcedureName,
  QglRequiredProcedure,
  QglRuntime,
  QglSymbolProvider,
  QwglDispatchTable,
  QwglInventoryProcedure,
  QwglProcedureName,
  QwglRuntime
} from "./qgl.js";
export type {
  glpoly_t,
  glpoly_vertex_t,
  image_t,
  medge_t,
  mleaf_t,
  mmodel_t,
  mnode_child_t,
  mnode_t,
  model_t,
  model_s,
  msurface_t,
  mtexinfo_t,
  mvertex_t
} from "./gl_model.js";
export type { GlModelHooks, GlModelRuntime, renderer_dvis_t } from "./gl_model.js";
export type { ThreeBeamSync } from "./three-beam-sync.js";
export type { ThreeDlightSync } from "./three-dlight-sync.js";
export type { ThreeGlDrawAdapter } from "./three-gl-draw-adapter.js";
export type { ThreePolyblendOverlay } from "./three-polyblend-overlay.js";
export type { Md2AliasEntityState, Md2MeshBuildOptions, Md2MeshInstance } from "./md2-mesh-builder.js";
export type { AliasShadeLightOptions } from "./gl_mesh.js";
export type { RefreshEntitySyncStats, ThreeRefreshEntitySync } from "./refresh-entity-sync.js";
export type { ThreeParticleSync } from "./particle-sync.js";
export type { LoadedQuakeSkyTextureSet, QuakeSkyResolver } from "./quake-sky-resolver.js";
export type { ThreeSkySceneAdapter } from "./sky-scene-adapter.js";
export type { RefGlBootstrap, RefGlBootstrapOptions } from "./ref-gl-bootstrap.js";
export type { RefGlHost, RefGlHostOptions } from "./ref-gl-host.js";
